/* TASK-048 (SB-007-B) — the forensics battery.
   TASK-050 (SB-007-C) — the criteria repair, per ruling R-8.

   This is the machine half of HV-DEFERRED-01. It does NOT discharge that debt:
   nobody has listened to the render, and no script can hear. What it does is
   narrow the maintainer's question from "is it broken?" to "is it good?" — the
   machine answers the first, the maintainer keeps the second (AMM-004 §4).

   SB-007-B ran this instrument for the first time and it went red on four
   criteria. The maintainer ruled (R-8) that three of them were the INSTRUMENT
   being wrong, not the audio:
     FND-01  export over full scale — a REAL audio defect (fixed by R-9's guard).
     FND-02  whole-file DC on non-stationary music — meaningless; gate silent
             regions only, where a bias is the only signal that can exist.
     FND-03  an interior-p99.9 count over-rejects by chance; judge it against its
             own Poisson distribution, and judge a single boundary against its own
             local neighbourhood.
     FND-04  the fake capture device cannot exercise onset/trim.
   The criteria below are therefore RE-DERIVED, not loosened. Every gated number
   was re-applied to the SAME audio evidence (R-8d): the SB-007-B record is read
   back and re-judged under the repaired rules, and a fresh render of the same
   factory Song is judged alongside it. Both verdicts are on record.

   Run:  bun run test:preview
   Writes .runs/evidence/sb007c/forensics.json (E-012: scratch, never the
   committed record — a later run must not be able to rewrite history).

   A FAIL here is a REAL FINDING, not a bad session (P-14). File it with a
   hypothesis in TASKS.md — never soften the threshold to make it pass. */

import { test, expect, type Page } from "@playwright/test";
import { mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import {
  poissonQuantile,
  LATTICE_NULL_RATE,
  LATTICE_POISSON_CONFIDENCE,
  LATTICE_ABSOLUTE_FLOOR,
  DC_SILENCE_WINDOW_MS,
} from "../../src/lib/forensics";

declare global {
  interface Window {
    app: any;
  }
}

const EVID = resolve(".runs/evidence/sb007c");
mkdirSync(EVID, { recursive: true });
const BEFORE_SB007B = resolve("docs/evidence/sb007b/forensics.json");

const PROXY =
  "PROXY — headless Chromium via playwright.launch, production bundle served by `vite preview`; " +
  "the microphone is Chromium's fake media device (a synthetic tone), not hardware. " +
  "The export is the app's own `engine.renderWav`; the take is the app's own trimmed WAV from OPFS media/.";

/* ---------- repaired criteria (R-8) ----------
   Thresholds live here, in the instrument, so a failing file cannot be talked
   green by passing softer numbers into the module (P-14). E-013: each carries
   its derivation + ruling. */

/** R-8a. The numeric value is UNCHANGED from the briefed criterion (1e-4); only
    the measurement DOMAIN changed (silent regions only). A repair must not move
    the number it was judged by, or the repair is indistinguishable from
    threshold-shopping. */
const MAX_SILENT_DC = 1e-4;
/** R-8c. A full-scale source legitimately touches 1.0; the briefed `clipped === 0`
    was unsatisfiable on one by construction (FND-04). */
const TAKE_PEAK_MIN = 0.98;
const TAKE_PEAK_MAX = 1.0;
/** R-8c. Take duration is judged against the armed wall-clock, not against an
    onset the fake device cannot express. */
const TAKE_DURATION_TOLERANCE_MS = 150;
/** R-8c. The export's own PREROLL lead-in is the meaningful trim check (it is
    generated by the offline render, not by a device). Tolerance unchanged. */
const MAX_TRIM_OFFSET_MS = 50;
/** R-9. Normalized delivery must land on the requested sample peak ±0.1 dB. */
const NORMALIZE_TOLERANCE_DB = 0.1;
/** Exactly-scripted key spacing, in ms, for the deterministic input path (R-8c). */
const MIDI_KEY_SPACING_MS = 70;
/** One model step — the tolerance for the deterministic input path's tick
    derivation (240 ticks ≈ 127 ms at 118 qpm). */
const STEP_TICKS = 240;

async function enterBench(page: Page): Promise<void> {
  await page.goto("/");
  await page.getByRole("button", { name: /launch the bench/i }).click();
  await page.waitForSelector(".bench");
}

/** The measured shape of one file: the numbers §4 of the briefing asks for,
    extended with the repaired criteria's own measurements. */
function numbers(report: any) {
  return {
    label: report.label,
    fileBytes: report.fileBytes,
    durationS: report.durationS,
    frames: report.frames,
    header: {
      fmtTag: report.header.fmtTag,
      fmtTagName: report.header.fmtTagName,
      channels: report.header.channels,
      sampleRate: report.header.sampleRate,
      bitsPerSample: report.header.bitsPerSample,
      blockAlignDeclared: report.header.blockAlignDeclared,
      blockAlignDerived: report.header.blockAlignDerived,
      byteRateDeclared: report.header.byteRateDeclared,
      byteRateDerived: report.header.byteRateDerived,
      declaredFieldsConsistent: report.header.declaredFieldsConsistent,
      dataBytesDeclared: report.header.dataBytesDeclared,
      dataBytesAvailable: report.header.dataBytesAvailable,
      dataFitsFile: report.header.dataFitsFile,
    },
    perChannel: report.channels.map((c: any) => ({
      index: c.index,
      /** Informational only (FND-02): the whole-file mean of a non-stationary file. */
      dcOffset: c.dcOffset,
      dcDbfs: c.dcDbfs,
      dcSegments: c.dcSegments.map((v: number) => Number(v.toExponential(6))),
      dcSegmentMaxAbs: c.dcSegmentMaxAbs,
      dcSegmentsMatchingOverallSign: c.dcSegmentsMatchingOverallSign,
      dcConcentration: c.dcConcentration,
      /** The GATED DC figure (R-8a). */
      dcSilent: {
        windowMs: c.dcSilent.windowMs,
        hopMs: c.dcSilent.hopMs,
        windowCount: c.dcSilent.windowCount,
        silentWindowCount: c.dcSilent.silentWindowCount,
        informative: c.dcSilent.informative,
        maxSilentAbsDc: c.dcSilent.maxSilentAbsDc,
        maxSilentDcDbfs: c.dcSilent.maxSilentDcDbfs,
        maxSilentRmsDbfs: c.dcSilent.maxSilentRmsDbfs,
        sampleSilentMeans: c.dcSilent.sampleSilentMeans.map((v: number) => Number(v.toExponential(6))),
      },
      truePeak: c.truePeak,
      truePeakDbfs: c.truePeakDbfs,
      clippedSamples: c.clippedSamples,
      samplesOverFullScale: c.samplesOverFullScale,
      maxBoundaryDelta: c.lattice.maxBoundaryDelta,
      maxBoundaryDeltaDbfs: c.lattice.maxBoundaryDeltaDbfs,
      interiorP999: c.lattice.interiorP999,
      interiorP999Dbfs: c.lattice.interiorP999Dbfs,
      boundaryCount: c.lattice.boundaryCount,
      outlierBoundaryCount: c.lattice.outlierBoundaries.length,
      outlierBoundaries: c.lattice.outlierBoundaries.slice(0, 16),
      /** Informational: the single-percentile criterion the repair replaced. */
      legacyLatticeVerdict: c.lattice.verdict,
      latticeGate: {
        informative: c.lattice.gate.informative,
        exceedanceCount: c.lattice.gate.exceedanceCount,
        poissonLambda: c.lattice.gate.poissonLambda,
        poissonAllowed: c.lattice.gate.poissonAllowed,
        countPass: c.lattice.gate.countPass,
        localCandidateCount: c.lattice.gate.localCandidateCount,
        localGuilty: c.lattice.gate.localGuilty,
        localPass: c.lattice.gate.localPass,
        pass: c.lattice.gate.pass,
        verdict: c.lattice.gate.verdict,
      },
    })),
    trim: {
      thresholdDbfs: report.trim.thresholdDbfs,
      expectedMs: report.trim.expectedMs,
      firstAudibleMs: report.trim.firstAudibleMs,
      offsetMs: report.trim.offsetMs,
      leadingSilenceMs: report.trim.leadingSilenceMs,
      trailingSilenceMs: report.trim.trailingSilenceMs,
    },
  };
}

/** Apply the REPAIRED criteria (R-8) to one file's measurements. Pure, so it can
    be applied to the SB-007-B record as well as to a fresh run (R-8d). */
function evaluate(report: any, kind: "export" | "take") {
  const silenceDc: number[] = report.channels.map((c: any) => c.dcSilent.maxSilentAbsDc);
  const silentInformative: boolean[] = report.channels.map((c: any) => !!c.dcSilent.informative);
  const dcPass = silentInformative.every(Boolean) && silenceDc.every((v) => v <= MAX_SILENT_DC);
  const latticeVerdicts: string[] = report.channels.map((c: any) => c.lattice.gate.verdict);
  // A PASS or an honestly-labelled UNINFORMATIVE both satisfy the gate; silence
  // must never masquerade as compliance (FND-03).
  const latticePass = latticeVerdicts.every((v) => v === "PASS" || v === "UNINFORMATIVE");
  const peaks: number[] = report.channels.map((c: any) => c.truePeak);
  const overFullScale = report.channels.reduce((n: number, c: any) => n + c.samplesOverFullScale, 0);
  return {
    kind,
    maxSilentAbsDc: silenceDc.length ? Math.max(...silenceDc) : null,
    silentWindows: report.channels.map((c: any) => c.dcSilent.silentWindowCount),
    /** FND-02's own derivation, from the OLD segment diagnostic: a genuine bias
        shows the same sign in every non-zero segment. */
    uniformBiasSegments: report.channels.map(
      (c: any) => `${c.dcSegmentsMatchingOverallSign}/${c.dcSegments.length}`
    ),
    dcPass,
    samplePeak: peaks.length ? Math.max(...peaks) : 0,
    samplesOverFullScale: overFullScale,
    latticeVerdicts,
    latticePass,
    trimOffsetMs: report.trim.offsetMs,
    // R-8c: trim is asserted on the export only; the fake device cannot express
    // an onset (FND-04), so the take's trim assertion is DELETED.
    trimPass: kind === "export" ? report.trim.offsetMs !== null && Math.abs(report.trim.offsetMs) <= MAX_TRIM_OFFSET_MS : null,
  };
}

test("TASK-050 — forensics under the repaired criteria (R-8), validated on the SAME evidence (R-8d)", async ({ page }) => {
  // The canonical fresh-state reset, so the "reference song" is the factory Song
  // and not whatever a previous test in this file left behind (P-02 / runbook HV-3).
  await enterBench(page);
  await page.evaluate(() => window.app.freshState());
  await page.reload();
  await page.getByRole("button", { name: /launch the bench/i }).click();
  await page.waitForSelector(".bench");

  /* ---- (a) the export path, AS-IS: the same audio SB-007-B measured ---- */
  const exportRes = await page.evaluate(() => window.app.forensics.renderReference());
  /* ---- (a') the SAME export, delivered through the R-9 guard (normalize) ---- */
  const normalizedRes = await page.evaluate(() =>
    window.app.forensics.renderReference(undefined, { peakPolicy: "normalize", targetDbfs: -1.0 })
  );

  /* ---- (b) the take path: record on the fake device, measure the armed
          wall-clock, then read it back (R-8c duration criterion) ---- */
  const armPressedAt = Date.now();
  await page.keyboard.press("r"); // record (P-22 default arms Keys + Voice)
  // The true "armed" moment: micCapture.reset() has run and the app reports it.
  await page.waitForFunction(() => window.app.ui().micArmed === true, null, { timeout: 5000 });
  const armedAt = Date.now();
  await page.waitForTimeout(2600); // 4-beat count-in at 118 qpm ≈ 2.03 s + margin
  for (const key of ["z", "x", "c", "v"]) {
    await page.keyboard.press(key);
    await page.waitForTimeout(MIDI_KEY_SPACING_MS);
  }
  const stopPressedAt = Date.now();
  await page.keyboard.press(" "); // stop → cmdFinishTake trims the count-in and writes media/<sha>.wav
  await page.waitForFunction(
    () => window.app.song().clips.some((c: any) => c.kind === "audio"),
    null,
    { timeout: 20_000 }
  );

  const takeRes = await page.evaluate(async () => {
    const song = window.app.song();
    const audio = song.clips.find((c: any) => c.kind === "audio");
    const midi = song.clips.find((c: any) => c.name.startsWith("Take"));
    if (!audio?.media) return { ok: false, error: "no audio clip with media" };
    // expected 0 ms: the count-in was trimmed from the front at capture time
    const res = await window.app.forensics.media(audio.media.sha, 0);
    const independent = await window.app.storage.probeMedia(audio.media.sha);
    return {
      ...res,
      sha: audio.media.sha,
      modelDurationS: audio.media.durationS,
      independent,
      mic: window.app.mic(),
      midiNotes: (midi?.notes ?? []).map((n: any) => ({ tick: n.tick, pitch: n.pitch })),
    };
  });

  expect(exportRes.ok, `export forensics failed: ${exportRes.error ?? ""}`).toBe(true);
  expect(normalizedRes.ok, `normalized export failed: ${normalizedRes.error ?? ""}`).toBe(true);
  expect(takeRes.ok, `take forensics failed: ${takeRes.error ?? ""}`).toBe(true);

  /* ---- duration criterion (R-8c): take vs the ARMED wall-clock, measured at the
          capture source. The in-page span is authoritative — the Node-side times
          are a cross-check, and the gap between them is itself recorded. ---- */
  const countInMs = (60 / 118) * 4 * 1000;
  const captureArmedWindowMs = takeRes.mic?.armedWindowMs ?? 0;
  const nodeArmedWallMs = stopPressedAt - armedAt; // diagnostic cross-check only
  const expectedTakeMs = captureArmedWindowMs - countInMs;
  const measuredTakeMs = takeRes.report.durationS * 1000;
  const durationDeltaMs = measuredTakeMs - expectedTakeMs;
  /** The armed window minus the kept take = the count-in region the trim removes. */
  const trimmedCountInRegionMs = captureArmedWindowMs - measuredTakeMs;
  expect(armPressedAt).toBeLessThanOrEqual(armedAt); // arm latch follows the keypress

  /* ---- deterministic input path (R-8c): the MIDI take's tick derivation ---- */
  const ticks: number[] = (takeRes.midiNotes ?? []).map((n: any) => n.tick);
  const tickDeltas = ticks.slice(1).map((t, i) => t - ticks[i]);
  const expectedTickDelta = (MIDI_KEY_SPACING_MS / 1000 / (60 / 118 / 960));
  const monotonic = tickDeltas.every((d) => d > 0);

  /* ---- normalized delivery (R-9): ±0.1 dB on the requested sample peak ---- */
  const normalizedPeak = normalizedRes.report.channels[0]?.truePeak ?? 0;
  const normalizedPeakDbfs = normalizedPeak > 0 ? 20 * Math.log10(normalizedPeak) : null;
  const normalizedDeltaDb = normalizedPeakDbfs === null ? null : normalizedPeakDbfs - normalizedRes.guard.targetDbfs;
  const normalizedClipped = normalizedRes.report.channels.reduce((n: number, c: any) => n + c.clippedSamples, 0);

  const exportEval = evaluate(exportRes.report, "export");
  const normalizedEval = evaluate(normalizedRes.report, "export");
  const takeEval = evaluate(takeRes.report, "take");

  /* ---- criteria check, collected rather than thrown on the first miss ---- */
  const failures: string[] = [];

  for (const [name, r] of [
    ["reference-song export", exportRes.report],
    ["normalized export", normalizedRes.report],
    ["fake-tone take", takeRes.report],
  ] as const) {
    if (r.header.container !== "RIFF/WAVE") failures.push(`${name}: container is ${r.header.container}`);
    if (r.header.fmtTagName !== "IEEE float" || r.header.bitsPerSample !== 32) {
      failures.push(`${name}: format is ${r.header.fmtTagName}/${r.header.bitsPerSample}-bit, expected IEEE float/32`);
    }
    if (!r.header.declaredFieldsConsistent) failures.push(`${name}: fmt declares inconsistent byteRate/blockAlign`);
    if (!r.header.dataFitsFile) failures.push(`${name}: data chunk overruns the file`);
    if (r.header.sampleRate !== 44100) failures.push(`${name}: sample rate ${r.header.sampleRate}`);
  }

  /* R-8a — DC gated inside silent windows only; whole-file DC informational. */
  for (const ev of [exportEval, normalizedEval, takeEval]) {
    if (!ev.dcPass) {
      failures.push(
        `${ev.kind}: silent-region DC not met — silentWindowCount ${JSON.stringify(ev.silentWindows)}, ` +
          `maxSilentAbsDc ${ev.maxSilentAbsDc} (limit ${MAX_SILENT_DC}); whole-file DC remains informational`
      );
    }
  }

  /* R-8b — lattice gate: Poisson count + local neighbourhood, not one percentile. */
  for (const ev of [exportEval, normalizedEval, takeEval]) {
    if (!ev.latticePass) failures.push(`${ev.kind}: lattice gate FAIL (${ev.latticeVerdicts.join(", ")})`);
  }

  /* R-9 — the guard must report the hot export honestly, and normalize must land. */
  if (!exportRes.guard.overFullScale) failures.push("R-9: the as-is export no longer exceeds full scale — FND-01 changed");
  if (exportRes.guard.warning === null) failures.push("R-9: as-is export is over 0 dBFS but carried no warning (P-14)");
  if (exportRes.guard.scaledByDb !== 0) failures.push(`R-9: as-is export applied ${exportRes.guard.scaledByDb} dB (P-15: no hidden gain move)`);
  if (normalizedDeltaDb === null || Math.abs(normalizedDeltaDb) > NORMALIZE_TOLERANCE_DB) {
    failures.push(`R-9: normalized delivery landed ${normalizedDeltaDb} dB from the −1.0 dB target (limit ±${NORMALIZE_TOLERANCE_DB})`);
  }
  if (normalizedClipped !== 0) failures.push(`R-9: normalized export still has ${normalizedClipped} clipped samples`);

  /* R-8c — take: peak range + armed-wall-clock duration; no onset assertion. */
  if (takeEval.samplePeak < TAKE_PEAK_MIN || takeEval.samplePeak > TAKE_PEAK_MAX) {
    failures.push(`fake-tone take: sample peak ${takeEval.samplePeak} outside [${TAKE_PEAK_MIN}, ${TAKE_PEAK_MAX}]`);
  }
  if (Math.abs(durationDeltaMs) > TAKE_DURATION_TOLERANCE_MS) {
    failures.push(
      `fake-tone take: duration ${measuredTakeMs.toFixed(1)} ms vs armed wall-clock ${expectedTakeMs.toFixed(1)} ms ` +
        `(Δ ${durationDeltaMs.toFixed(1)} ms > ±${TAKE_DURATION_TOLERANCE_MS} ms; capture window ${captureArmedWindowMs.toFixed(1)} ms, ` +
        `trimmed count-in region ${trimmedCountInRegionMs.toFixed(1)} ms)`
    );
  }

  /* R-8c — export trim (the meaningful one) still holds. */
  if (exportEval.trimPass !== true) {
    failures.push(
      `reference-song export: onset ${exportRes.report.trim.firstAudibleMs?.toFixed(1)} ms vs expected ` +
        `${exportRes.report.trim.expectedMs} ms (offset ${exportRes.report.trim.offsetMs?.toFixed(1)} ms > ±${MAX_TRIM_OFFSET_MS} ms)`
    );
  }

  /* R-8c — deterministic input path: musical typing's tick derivation is asserted
     HERE, off the fake device. */
  if (!monotonic) failures.push(`deterministic input path: MIDI ticks are not strictly increasing (${JSON.stringify(ticks)})`);
  if (ticks.length !== 4) failures.push(`deterministic input path: expected 4 captured notes, got ${ticks.length}`);
  for (const d of tickDeltas) {
    if (Math.abs(d - expectedTickDelta) > STEP_TICKS) {
      failures.push(
        `deterministic input path: tick delta ${d} vs scripted ${expectedTickDelta.toFixed(0)} (tolerance ±${STEP_TICKS} ticks)`
      );
    }
  }

  /* ---- R-8d: re-apply the repaired criteria to the SAME evidence ---- */
  const before = existsSync(BEFORE_SB007B) ? JSON.parse(readFileSync(BEFORE_SB007B, "utf8")) : null;
  const beforeExportCh0 = before?.referenceSongExport?.perChannel?.[0];
  const beforeTakeCh0 = before?.fakeToneMicTake?.perChannel?.[0];
  const beforeLambda = beforeExportCh0 ? LATTICE_NULL_RATE * beforeExportCh0.boundaryCount : null;
  const validation = {
    mandate:
      "R-8d — the repaired criteria are validated on the SAME audio evidence: the SB-007-B record is read back and " +
      "re-judged under the repaired rules, and a fresh render of the same factory Song is judged alongside it.",
    source: existsSync(BEFORE_SB007B) ? "docs/evidence/sb007b/forensics.json" : "absent",
    FND_01: {
      ruling: "R-9 (real audio defect — the guard is the fix; the mix itself is TASK-054's maintainer call, P-15)",
      before: beforeExportCh0
        ? {
            criterion: "clippedSamples === 0",
            verdict: "FAIL (real)",
            samplePeak: beforeExportCh0.truePeak,
            measuredPeakDbfs: beforeExportCh0.truePeakDbfs,
            samplesOverFullScale: beforeExportCh0.samplesOverFullScale,
          }
        : null,
      after: {
        criterion: "as-is carries a measurable warning AND normalized delivery lands within ±0.1 dB with 0 clipped samples",
        verdict: failures.some((f) => f.startsWith("R-9")) ? "FAIL" : "PASS",
        asIsSamplePeak: exportRes.guard.samplePeak,
        asIsPeakDbfs: exportRes.guard.measuredPeakDbfs,
        asIsWarning: exportRes.guard.warning,
        normalizedPeakDbfs: normalizedPeakDbfs,
        normalizedDeltaDb,
        normalizedClipped,
      },
    },
    FND_02: {
      ruling: "R-8a (instrument defect, authored by the maintainer — whole-file DC is invalid on non-stationary music)",
      before: beforeExportCh0
        ? {
            criterion: "|whole-file DC| ≤ 1e-4",
            verdict: "FAIL (instrument)",
            wholeFileDc: beforeExportCh0.dcOffset,
            dcDbfs: beforeExportCh0.dcDbfs,
            segmentMeans: beforeExportCh0.dcSegments,
            uniformBiasCheck: `${beforeExportCh0.dcSegmentsMatchingOverallSign}/${beforeExportCh0.dcSegments.length} segments share the overall sign — a constant bias would show all of them`,
          }
        : null,
      after: {
        criterion: `DC gated on ${DC_SILENCE_WINDOW_MS} ms windows below −60 dBFS RMS only`,
        verdict: exportEval.dcPass && takeEval.dcPass ? "PASS" : "FAIL",
        exportSilentWindows: exportEval.silentWindows,
        exportMaxSilentAbsDc: exportEval.maxSilentAbsDc,
        takeSilentWindows: takeEval.silentWindows,
        takeMaxSilentAbsDc: takeEval.maxSilentAbsDc,
      },
    },
    FND_03: {
      ruling: "R-8b (instrument defect, authored by the maintainer — a single interior percentile has a built-in false-positive rate)",
      before: beforeExportCh0
        ? {
            criterion: "outlierBoundaries.length === 0 vs the interior p99.9",
            verdict: "FAIL (instrument)",
            boundaryCount: beforeExportCh0.boundaryCount,
            exceedances: beforeExportCh0.outlierBoundaryCount,
            expectedByChance: beforeExportCh0.expectedOutliersByChance,
            poissonLambda: beforeLambda,
            poissonAllowed: beforeLambda === null ? null : poissonQuantile(beforeLambda, LATTICE_POISSON_CONFIDENCE),
            maxBoundaryDelta: beforeExportCh0.maxBoundaryDelta,
            interiorP999: beforeExportCh0.interiorP999,
            absoluteFloor: LATTICE_ABSOLUTE_FLOOR,
          }
        : null,
      after: {
        criterion: "Poisson count gate + ±1 s local-outlier gate; interiorP999 = 0 reported UNINFORMATIVE, never a silent pass",
        verdict: exportEval.latticePass && takeEval.latticePass ? "PASS" : "FAIL",
        exportGate: exportRes.report.channels[0].lattice.gate,
        takeGate: takeRes.report.channels[0].lattice.gate,
      },
    },
    FND_04: {
      ruling: "R-8c (platform instrument defect — the fake device cannot exercise onset/trim)",
      before: {
        criterion: "take onset vs expected 0 ms, ±50 ms",
        verdict: "FAIL (instrument, non-deterministic: 0.0 / 446.4 / 0.0 ms across runs)",
      },
      after: {
        criterion: "take peak ∈ [0.98, 1.0] + duration vs ARMED wall-clock ±150 ms; onset assertion DELETED; sub-step timing verified on the deterministic MIDI input path",
        verdict: durationDeltaMs !== null && Math.abs(durationDeltaMs) <= TAKE_DURATION_TOLERANCE_MS ? "PASS" : "FAIL",
        captureArmedWindowMs,
        nodeArmedWallMs,
        trimmedCountInRegionMs,
        countInMs,
        expectedTakeMs,
        measuredTakeMs,
        durationDeltaMs,
        midiNotes: ticks.length,
        midiTickDeltas: tickDeltas,
        expectedTickDelta,
      },
    },
  };

  writeFileSync(
    resolve(EVID, "forensics.json"),
    JSON.stringify(
      {
        proxy: PROXY,
        thresholds: {
          maxSilentDc: MAX_SILENT_DC,
          takePeakMin: TAKE_PEAK_MIN,
          takePeakMax: TAKE_PEAK_MAX,
          takeDurationToleranceMs: TAKE_DURATION_TOLERANCE_MS,
          maxTrimOffsetMs: MAX_TRIM_OFFSET_MS,
          normalizeToleranceDb: NORMALIZE_TOLERANCE_DB,
          latticeNullRate: LATTICE_NULL_RATE,
          latticePoissonConfidence: LATTICE_POISSON_CONFIDENCE,
          latticeAbsoluteFloor: LATTICE_ABSOLUTE_FLOOR,
        },
        referenceSongExport: numbers(exportRes.report),
        normalizedExport: numbers(normalizedRes.report),
        fakeToneMicTake: { ...numbers(takeRes.report), sha: takeRes.sha, modelDurationS: takeRes.modelDurationS, midiNotes: takeRes.midiNotes },
        exportGuard: exportRes.guard,
        parserCrossCheck: {
          independentReader: "window.app.storage.probeMedia → probeWav (TASK-021)",
          independentProbe: takeRes.independent?.probe ?? takeRes.independent,
          agree: {
            channels: takeRes.report.header.channels === takeRes.independent?.probe?.channels,
            sampleRate: takeRes.report.sampleRate === takeRes.independent?.probe?.sampleRate,
            frames: takeRes.report.frames === takeRes.independent?.probe?.frames,
            truePeak: takeRes.report.channels[0].truePeak === takeRes.independent?.probe?.peak,
          },
        },
        evaluation: { export: exportEval, normalized: normalizedEval, take: takeEval },
        validation,
        criteriaNotMet: failures,
        verdict: failures.length === 0 ? "PASS" : "FAIL",
        disclosure:
          "PROXY, and a deliberately limited one. The take is Chromium's fake media device, which emits a " +
          "short full-scale square burst inside digital silence: the peak/duration criteria are meaningful, but the " +
          "burst train makes the take's DC and lattice numbers weak (the lattice gate reports UNINFORMATIVE when the " +
          "interior p99.9 is 0, rather than passing silently). The export's DC, lattice and trim checks are the " +
          "meaningful ones. Neither file has been heard by anyone: HV-DEFERRED-01 is narrowed, not cleared.",
      },
      null,
      2
    ) + "\n"
  );

  /* ---- structural facts that must hold regardless of the criteria ---- */
  expect(exportRes.report.header.channels).toBe(2); // the mix is stereo
  expect(takeRes.report.header.channels).toBe(1); // the capture is mono

  // The two readers must agree, or the forensics numbers describe nothing real.
  const probe = takeRes.independent?.probe;
  expect(probe, "independent parser produced no probe").toBeTruthy();
  expect(takeRes.report.header.channels).toBe(probe.channels);
  expect(takeRes.report.sampleRate).toBe(probe.sampleRate);
  expect(takeRes.report.frames).toBe(probe.frames);
  expect(takeRes.report.channels[0].truePeak).toBe(probe.peak);

  expect(
    failures,
    `${failures.length} repaired criterion(s) not met — each one is a finding to file, not a threshold to move:\n` +
      failures.map((f, i) => `  ${i + 1}. ${f}`).join("\n")
  ).toEqual([]);
});
